#!/bin/sh 

if [ -d indico/translations ]; then
	PRE=indico/translations
fi

for l in ./$PRE/[a-jn-z]*
	do 
		if [ ! -d $l/LC_MESSAGES ]; then
			continue
		fi
		basename $l
		for r in $l/LC*/m*po; do 
			msgid=$(($(grep msgid\  $r| wc -l) -1))
			msgid_plu=$(grep msgid_plu $r | wc -l)
			msgstr=$(($(grep msgstr' ""' $r | wc -l) -1))
			msgstr_plu=$(($(grep msgstr'\[[01]\] ""' $r | wc -l) /2))
			echo $(basename $l)::$(basename $r) $msgid msgs \($msgid_plu plu\) $msgstr $msgstr_plu
		done 
	done

